if(xClaimSettings==undefined){var xClaimSettings={ 

        JSONPCallback: "JSONPCallback",
        SearchingDiv: "intextAd",
        SearchingId: "__xclaimwords_wrapper",
        xClaimTopElementId: "xClaimTopElement",
        iFrameHolderDivID: "xClaimPostIframe",
        iframeName: "xClaimPost",
        formInputTextName: "rijeci",
        formInputUrlName: "url",
        formInputOglasIdName: "oglasid",
        formInputPartnerIdName: "partnerid",
        CrossDomainSubmitTime: 10000,
        xClaimOblacicClass: "xClaimOblacicClass",
        mScriptLimit: "5000",
        mSkipTags: /^(head|title|script|style|textarea|iframe|noscript|select|noembed|object|embed|a|link|button|pre)/i,
        mTestWordEnd: " ;.!?,'\":-",
        mClassa: "xClaimClass",
        origText: [["<!--(.*?)-->", "gi"], ["<[^>]*>", "gi"], ["[^a-zA-Z0-9_čćžđšŽĆČŠĐÓóĄąĘęŁłŃńŚśŹźŻż]", "gi"], ["&.*;", "gi"], ["\\s", "gi"]],
        replText: [" ", " ", " ", " ", " "],
        OglasIdPrefix: "xClaimOglasId-",
        OblacicIdPrefix: "xClaimOblacicId-",
        ClientMarginPaddingTop: 0,
        ClientMarginPaddingLeft: 0,
        OblacicFixElements: "iframe|object|embed",
        TimeBeforeOpen: 100,
        TimeBeforeClose: 800,
        DragAndDrop:true,
        OglasPozicijaTop: 0,
        OglasPozicijaLeft: 0,
        postRijeci: false,
        CheckParentsRecursionLimit: 0,
        IframeJsData: "http://hr-engine.xclaimwords.net/frame.html?frameData=",
        TimeBeforeDisplayOglasiNew: 2000,
        TimeBeforeDisplayOglasiPrepared: 1000,
        StatistikaImg: "http://hr-engine.xclaimwords.net/view.gif?",
        ProzorFlash: "http://hr-engine.xclaimwords.net/FlashObject/master.swf",
        CrossDomainPost: "http://hr-engine.xclaimwords.net/CrossPostPage.xclaim",
        jsonpUrl: "http://hr-engine.xclaimwords.net/GetWords.xclaim",
        generalScriptUrl: "http://hr-engine.xclaimwords.net/static.js",
        xClaimCss: "http://hr-engine.xclaimwords.net/css/xclaim.css",
        brojRijeci: 700,
        Partner: {"Id":116455,"Link":"http://www.slobodnadalmacija.hr","BrojRijeci":6,"StyleRijeci":"","CustomLogo":"http://hr-engine.xclaimwords.net/img/logo.png","CustomLogoLink":"http://www.xclaim.hr/","SecureUnderineActive":false,"OffsetX":0,"OffsetY":0,"TestPartner":false,"PartnerAktivan":true},
        Oglasi: []
         };var fileref=document.createElement('script');fileref.setAttribute("type","text/javascript");fileref.setAttribute("src",xClaimSettings.generalScriptUrl);if(typeof fileref!="undefined");document.getElementsByTagName("head")[0].appendChild(fileref);var fileref=document.createElement("link");fileref.setAttribute("rel","stylesheet");fileref.setAttribute("type","text/css");fileref.setAttribute("href",xClaimSettings.xClaimCss);document.getElementsByTagName("head")[0].appendChild(fileref)}